#!/usr/bin/env python3
"""emit_csharp.py -- turn gen_vectors output into the pinned C# fixture.

Reads the JSON that gen_vectors printed on stdin and writes a C# source file. It
performs no arithmetic on the values: every number in the output file came out of the
upstream reference implementation. Transcription by hand is exactly the step where a
digit gets dropped and the resulting "reference vector" pins a bug forever.

    tools/pcg-vectors/generate.sh          regenerate the fixture
    tools/pcg-vectors/generate.sh --check  fail if the committed fixture has drifted

This is a code generator, not a checked-in copy of anything upstream: the vectors are
facts about an algorithm, and facts are not the reference implementation's source code.
"""
from __future__ import annotations

import argparse
import json
import sys

HEADER = """// <auto-generated>
//   Generated by tools/pcg-vectors/generate.sh. Do not edit by hand.
//
//   Every value below was produced by the upstream PCG reference implementation
//   (imneme/pcg-c-basic, pcg_basic.c) at commit
//       {commit}
//   fetched and hash-verified by that script, compiled locally, and called through its
//   published API. None of it was recalled, copied from documentation, or read out of
//   another language's port.
//
//   The "canonical-42-54" row is additionally checkable against a file this repository
//   did not produce: upstream's own test-high/expected/check-pcg32.out records the same
//   six leading outputs for the same seed.
//
//   Regenerating: tools/pcg-vectors/generate.sh   (needs a C compiler and network)
//   Verifying:    tools/pcg-vectors/generate.sh --check
// </auto-generated>

using System.Collections.Generic;

namespace RulesKernel.Randomness.Tests;

/// <summary>
/// PCG32 (<c>pcg_setseq_64_xsh_rr_32</c>) sequences taken from the reference
/// implementation. These are the replay contract: if a change here is not accompanied by
/// a decision superseding docs/decisions/0005, the change is a bug, because every stored seed in the
/// project means whatever this file says it means.
/// </summary>
public static class Pcg32ReferenceVectors
{{
    /// <summary>The upstream commit the vectors were generated from.</summary>
    public const string UpstreamCommit = "{commit}";

    /// <summary>The upstream repository the reference implementation was fetched from.</summary>
    public const string UpstreamRepository = "{repo}";

    /// <summary>A sequence produced by seeding the reference with an explicit state and stream.</summary>
    /// <param name="Name">Identifies the row in assertion output.</param>
    /// <param name="InitState">The <c>initstate</c> argument to <c>pcg32_srandom_r</c>.</param>
    /// <param name="InitSequence">The <c>initseq</c> (stream selector) argument.</param>
    /// <param name="StateAfterSeed">The reference's internal state once seeding returned.</param>
    /// <param name="IncrementAfterSeed">The reference's internal increment once seeding returned.</param>
    /// <param name="Outputs">Consecutive <c>pcg32_random_r</c> results from that point.</param>
    public sealed record SeededVector(
        string Name,
        ulong InitState,
        ulong InitSequence,
        ulong StateAfterSeed,
        ulong IncrementAfterSeed,
        IReadOnlyList<uint> Outputs);

    /// <summary>A sequence produced by driving the reference from an explicit (state, increment) pair.</summary>
    /// <param name="Name">Identifies the row in assertion output.</param>
    /// <param name="State">The internal state the reference was started from.</param>
    /// <param name="Increment">The internal increment the reference was started from.</param>
    /// <param name="RotOfFirstDraw">The rotation the first draw applies; 0 and 31 are the edge cases.</param>
    /// <param name="Outputs">Consecutive <c>pcg32_random_r</c> results from that point.</param>
    /// <param name="StateAfter">The reference's internal state after those draws.</param>
    /// <param name="IncrementAfter">The reference's internal increment after those draws.</param>
    public sealed record RawStateVector(
        string Name,
        ulong State,
        ulong Increment,
        int RotOfFirstDraw,
        IReadOnlyList<uint> Outputs,
        ulong StateAfter,
        ulong IncrementAfter);

    /// <summary>A capture taken mid-sequence, with the draws that must follow it.</summary>
    /// <param name="Name">Identifies the row in assertion output.</param>
    /// <param name="InitState">The <c>initstate</c> argument to <c>pcg32_srandom_r</c>.</param>
    /// <param name="InitSequence">The <c>initseq</c> (stream selector) argument.</param>
    /// <param name="Skip">How many values were drawn and discarded before the capture.</param>
    /// <param name="StateAtCapture">The reference's internal state at that moment.</param>
    /// <param name="IncrementAtCapture">The reference's internal increment at that moment.</param>
    /// <param name="OutputsAfterCapture">Consecutive results the capture must go on to produce.</param>
    public sealed record ResumeVector(
        string Name,
        ulong InitState,
        ulong InitSequence,
        int Skip,
        ulong StateAtCapture,
        ulong IncrementAtCapture,
        IReadOnlyList<uint> OutputsAfterCapture);
"""

FOOTER = "}\n"


def hex64(value: str) -> str:
    return f"0x{int(value, 16):016X}UL"


def outputs(values: list[str], indent: str) -> str:
    """Render 32-bit outputs four to a line, so a diff points at a short row."""
    literals = [f"0x{int(v, 16):08X}U" for v in values]
    lines = [
        ", ".join(literals[i:i + 4]) + ("," if i + 4 < len(literals) else "")
        for i in range(0, len(literals), 4)
    ]
    body = f"\n{indent}    ".join(lines)
    return f"[\n{indent}    {body}\n{indent}]"


def render_seeded(vectors: list[dict]) -> str:
    rows = []
    for v in vectors:
        rows.append(
            "        new(\n"
            f'            "{v["name"]}",\n'
            f"            {hex64(v['initstate'])},\n"
            f"            {hex64(v['initseq'])},\n"
            f"            {hex64(v['state_after_seed'])},\n"
            f"            {hex64(v['inc_after_seed'])},\n"
            f"            {outputs(v['outputs'], '            ')}),"
        )
    joined = "\n".join(rows)
    return (
        "\n    /// <summary>Sequences reached through the reference's own seeding routine.</summary>\n"
        "    public static readonly IReadOnlyList<SeededVector> Seeded =\n"
        "    [\n"
        f"{joined}\n"
        "    ];\n"
    )


def render_raw(vectors: list[dict]) -> str:
    rows = []
    for v in vectors:
        rows.append(
            "        new(\n"
            f'            "{v["name"]}",\n'
            f"            {hex64(v['state'])},\n"
            f"            {hex64(v['inc'])},\n"
            f"            {v['rot_of_first_draw']},\n"
            f"            {outputs(v['outputs'], '            ')},\n"
            f"            {hex64(v['state_after'])},\n"
            f"            {hex64(v['inc_after'])}),"
        )
    joined = "\n".join(rows)
    return (
        "\n    /// <summary>Sequences reached by restoring an explicit internal state.</summary>\n"
        "    public static readonly IReadOnlyList<RawStateVector> RawState =\n"
        "    [\n"
        f"{joined}\n"
        "    ];\n"
    )


def render_resume(vectors: list[dict]) -> str:
    rows = []
    for v in vectors:
        rows.append(
            "        new(\n"
            f'            "{v["name"]}",\n'
            f"            {hex64(v['initstate'])},\n"
            f"            {hex64(v['initseq'])},\n"
            f"            {v['skip']},\n"
            f"            {hex64(v['state_at_capture'])},\n"
            f"            {hex64(v['inc_at_capture'])},\n"
            f"            {outputs(v['outputs_after_capture'], '            ')}),"
        )
    joined = "\n".join(rows)
    return (
        "\n    /// <summary>Mid-sequence captures and the draws that must follow them.</summary>\n"
        "    public static readonly IReadOnlyList<ResumeVector> Resume =\n"
        "    [\n"
        f"{joined}\n"
        "    ];\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="emit_csharp.py", description=__doc__.splitlines()[0])
    parser.add_argument("--commit", required=True, help="upstream commit the vectors came from")
    parser.add_argument("--repository", required=True, help="upstream repository URL")
    parser.add_argument("--out", required=True, help="C# file to write")
    args = parser.parse_args(argv)

    payload = json.loads(sys.stdin.read().replace(",\n    null", ""))
    vectors = payload["vectors"]

    by_kind: dict[str, list[dict]] = {"seeded": [], "raw": [], "resume": []}
    for vector in vectors:
        by_kind[vector["kind"]].append(vector)

    for kind, rows in by_kind.items():
        if not rows:
            raise SystemExit(f"gen_vectors emitted no '{kind}' vectors; refusing to write a fixture")

    text = (
        HEADER.format(commit=args.commit, repo=args.repository)
        + render_seeded(by_kind["seeded"])
        + render_raw(by_kind["raw"])
        + render_resume(by_kind["resume"])
        + FOOTER
    )

    with open(args.out, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
