#!/usr/bin/env bash
# generate.sh -- produce and verify the PCG32 reference vectors.
#
# tests/RulesKernel.Randomness.Tests/Pcg32ReferenceVectors.cs says at the top of the file
# that it was generated by this script and must not be edited by hand. That sentence was a
# promise with nothing behind it: the script did not exist, and tools/repo-checks.py could
# not see the dangling citation because its reference check only looked at docs/*.md.
#
#   tools/pcg-vectors/generate.sh --check    verify the committed vectors (exit 1 on drift)
#   tools/pcg-vectors/generate.sh            print freshly generated vectors to stdout
#
# Both modes need a C compiler and network access, because both fetch and compile the
# upstream reference implementation. Neither is run by scripts/validate.sh: the gate must
# work for anyone who can clone the repository, with no network beyond NuGet restore.
# Run this by hand when a vector is added or when the pin below is changed.
#
# Why compile upstream C rather than assert the numbers: the vectors ARE the replay
# contract (docs/decisions/0005). Every stored seed downstream means whatever that file
# says it means. A number recalled from memory, copied out of documentation, or read from
# another language's port would be an assertion; a number produced by calling upstream's
# own published API is evidence.
#
# This script does NOT edit the .cs file. It prints, or it compares and reports. A
# generator that rewrites its own evidence on every run makes drift invisible, which is
# the failure this file exists to prevent.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
VECTORS_CS="$REPO_ROOT/tests/RulesKernel.Randomness.Tests/Pcg32ReferenceVectors.cs"

# The upstream pin. A raw.githubusercontent URL carrying a commit SHA is already
# content-addressed -- git's own hash covers the bytes -- so the sha256 values below are a
# second, independent statement of the same fact. They are here so that a mirror, a proxy,
# or a future change to how GitHub serves raw files cannot substitute different bytes
# without this script saying so.
UPSTREAM_REPO="https://github.com/imneme/pcg-c-basic"
UPSTREAM_COMMIT="bc39cd76ac3d541e618606bcc6e1e5ba5e5e6aa3"
SHA256_PCG_BASIC_C="b6582a071a8a090a293621523c063d125a532d772a2a1eb7d60b3e695fe47746"
SHA256_PCG_BASIC_H="cd823ddc225da9be520a54f13ef2c491506c353800cae04e8b673b2de58f2cc4"

# The inputs each vector is generated from. The outputs are never written here -- they come
# out of the reference implementation, which is the entire point. Columns:
#
#   seeded <name> <initstate> <initseq> <draws>
#       call pcg32_srandom_r(initstate, initseq), record the resulting (state, inc), then
#       record <draws> consecutive pcg32_random_r results.
#   raw <name> <state> <inc> <draws>
#       start from an explicit internal (state, inc) with no seeding call, record <draws>
#       results, then record the internal state afterwards.
#   resume <name> <initstate> <initseq> <skip> <draws>
#       seed, draw and discard <skip> values, record the internal state at that moment,
#       then record <draws> further results.
#
# Values are C literals so the C compiler parses them, not this shell.
VECTOR_SPEC=$(cat <<'SPEC'
seeded canonical-42-54      0x2AULL                0x36ULL                16
seeded zero-zero            0x0ULL                 0x0ULL                 16
seeded one-one              0x1ULL                 0x1ULL                 16
seeded max-state-max-seq    0xFFFFFFFFFFFFFFFFULL  0xFFFFFFFFFFFFFFFFULL  16
seeded high-entropy         0x853C49E6748FEA9BULL  0xDA3E39CB94B95BDBULL  16
seeded stream-a             0x2AULL                0x0ULL                 8
seeded stream-b             0x2AULL                0x1ULL                 8
seeded stream-c             0x2AULL                0x2ULL                 8
raw    initializer          0x853C49E6748FEA9BULL  0xDA3E39CB94B95BDBULL  8
raw    rot-zero             0x0ULL                 0x1ULL                 8
raw    rot-max              0xFFFFFFFFFFFFFFFFULL  0x1ULL                 8
resume resume-42-54         0x2AULL                0x36ULL                5    8
resume resume-canonical-long 0x2AULL               0x36ULL                100  8
SPEC
)

MODE="${1:---print}"
case "$MODE" in
  --check|--print) ;;
  *) printf 'usage: %s [--check]\n' "$0" >&2; exit 2 ;;
esac

for tool in cc curl sha256sum; do
  command -v "$tool" >/dev/null 2>&1 || { printf 'generate.sh: %s is required\n' "$tool" >&2; exit 2; }
done

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

fetch() {
  local name="$1" expected="$2"
  curl -sSfL -o "$WORK/$name" \
    "https://raw.githubusercontent.com/imneme/pcg-c-basic/$UPSTREAM_COMMIT/$name"
  local actual
  actual="$(sha256sum "$WORK/$name" | cut -d' ' -f1)"
  if [[ "$actual" != "$expected" ]]; then
    printf 'generate.sh: %s from %s@%s hashes %s, expected %s\n' \
      "$name" "$UPSTREAM_REPO" "$UPSTREAM_COMMIT" "$actual" "$expected" >&2
    exit 1
  fi
}

fetch pcg_basic.c "$SHA256_PCG_BASIC_C"
fetch pcg_basic.h "$SHA256_PCG_BASIC_H"

# The harness is written here rather than kept as a committed .c file so that this
# directory holds one artefact instead of two that can disagree.
{
  cat <<'PROLOGUE'
#include <stdio.h>
#include <inttypes.h>
#include "pcg_basic.h"

static void seeded(const char *name, uint64_t s, uint64_t q, int draws) {
    pcg32_random_t r;
    pcg32_srandom_r(&r, s, q);
    printf("seeded %s %016" PRIX64 " %016" PRIX64 " %016" PRIX64 " %016" PRIX64,
           name, s, q, r.state, r.inc);
    for (int i = 0; i < draws; i++) printf(" %08" PRIX32, pcg32_random_r(&r));
    printf("\n");
}

static void raw(const char *name, uint64_t state, uint64_t inc, int draws) {
    pcg32_random_t r;
    r.state = state;
    r.inc = inc;
    /* The rotation the first draw applies, computed the way pcg_basic.c computes it:
       the top five bits of the state BEFORE that draw advances it. Recorded because 0
       and 31 are the edge cases of the rotate, and a port that gets the rotate direction
       wrong agrees with the reference everywhere except there. */
    int rot = (int)(state >> 59u);
    printf("raw %s %016" PRIX64 " %016" PRIX64 " %d", name, state, inc, rot);
    for (int i = 0; i < draws; i++) printf(" %08" PRIX32, pcg32_random_r(&r));
    printf(" %016" PRIX64 " %016" PRIX64 "\n", r.state, r.inc);
}

static void resume(const char *name, uint64_t s, uint64_t q, int skip, int draws) {
    pcg32_random_t r;
    pcg32_srandom_r(&r, s, q);
    for (int i = 0; i < skip; i++) (void)pcg32_random_r(&r);
    printf("resume %s %016" PRIX64 " %016" PRIX64 " %d %016" PRIX64 " %016" PRIX64,
           name, s, q, skip, r.state, r.inc);
    for (int i = 0; i < draws; i++) printf(" %08" PRIX32, pcg32_random_r(&r));
    printf("\n");
}

int main(void) {
PROLOGUE
  while read -r kind name a b c d; do
    [[ -z "${kind:-}" ]] && continue
    case "$kind" in
      seeded) printf '    seeded("%s", %s, %s, %s);\n' "$name" "$a" "$b" "$c" ;;
      raw)    printf '    raw("%s", %s, %s, %s);\n' "$name" "$a" "$b" "$c" ;;
      resume) printf '    resume("%s", %s, %s, %s, %s);\n' "$name" "$a" "$b" "$c" "$d" ;;
    esac
  done <<< "$VECTOR_SPEC"
  printf '    return 0;\n}\n'
} > "$WORK/harness.c"

cc -std=c99 -O2 -Wall -o "$WORK/harness" "$WORK/harness.c" "$WORK/pcg_basic.c" -I"$WORK"
"$WORK/harness" > "$WORK/generated.txt"

if [[ "$MODE" == "--print" ]]; then
  printf '# %s@%s\n' "$UPSTREAM_REPO" "$UPSTREAM_COMMIT"
  printf '# kind name <inputs...> <state/inc...> <outputs...>, all hex, uppercase\n'
  cat "$WORK/generated.txt"
  printf '\n# This script does not edit %s.\n' "${VECTORS_CS#"$REPO_ROOT/"}" >&2
  exit 0
fi

# --check: read the committed C# file back into the same record shape and compare. The
# parser is deliberately shape-blind -- it takes the hex literals in source order out of
# each record -- so a reordering of the file's fields shows up as a mismatch rather than
# being silently accommodated.
python3 - "$VECTORS_CS" "$WORK/generated.txt" <<'PY'
import re
import sys

source = open(sys.argv[1], encoding="utf-8").read()
generated = open(sys.argv[2], encoding="utf-8").read().split("\n")

# Each `new(` record runs to the matching close; taking the hex literals in order gives
# the same sequence the harness printed, because both follow the declaration order of the
# record types.
# Slice the file at each `new("<name>"` and read to the start of the next one: a single
# regex with .*? spans records, which silently merged four vectors into one.
records = {}
starts = [(m.start(), m.group(1), m.end()) for m in re.finditer(r'new\(\s*"([^"]+)"', source)]
for index, (_start, name, after) in enumerate(starts):
    end = starts[index + 1][0] if index + 1 < len(starts) else len(source)
    body = source[after:end]
    values = [v.upper() for v in re.findall(r"0x([0-9A-Fa-f]+)U?L?L?\b", body)]
    plain = re.findall(r"(?<![\w.])(\d+)(?![\w.])", body)
    records[name] = (values, plain, body)

problems = []
seen = set()
for line in generated:
    if not line.strip():
        continue
    fields = line.split()
    kind, name, rest = fields[0], fields[1], fields[2:]
    seen.add(name)
    if name not in records:
        problems.append(f"{name}: generated by the reference but absent from the C# file")
        continue
    values, plain, body = records[name]
    actual = [v.lstrip("0") or "0" for v in values]
    # The harness prints every 64-bit field as 16 hex digits and every draw as 8, so a
    # field of some other width is the one decimal column a record carries: `raw`'s
    # rotation, `resume`'s skip count. Those are compared separately, below.
    hex_fields = [f for f in rest if re.fullmatch(r"[0-9A-F]{8}|[0-9A-F]{16}", f)]
    decimals = [f for f in rest if f not in hex_fields]
    expected = [f.lstrip("0") or "0" for f in hex_fields]
    if expected != actual:
        problems.append(
            f"{name}: {len(actual)} hex value(s) in the C# file, "
            f"{len(expected)} from the reference; first difference at "
            + next((f"index {i} (file 0x{a}, reference 0x{e})"
                    for i, (a, e) in enumerate(zip(actual, expected)) if a != e),
                   "the end -- the lengths differ")
        )
    for decimal in decimals:
        if decimal not in plain:
            problems.append(
                f"{name}: the reference reports {decimal} "
                "(rotation or skip count) and the C# file does not record it"
            )

for name in sorted(set(records) - seen):
    problems.append(f"{name}: in the C# file but not produced by this script's VECTOR_SPEC")

if problems:
    print("generate.sh --check: the committed vectors do not match the reference")
    for problem in problems:
        print(f"  {problem}")
    raise SystemExit(1)
print(f"generate.sh --check: {len(seen)} vector(s) match the reference implementation")
PY
