// <auto-generated>
//   Generated by tools/pcg-vectors/generate.sh. Do not edit by hand.
//
//   Every value below was produced by the upstream PCG reference implementation
//   (imneme/pcg-c-basic, pcg_basic.c) at commit
//       bc39cd76ac3d541e618606bcc6e1e5ba5e5e6aa3
//   fetched and hash-verified by that script, compiled locally, and called through its
//   published API. None of it was recalled, copied from documentation, or read out of
//   another language's port.
//
//   The "canonical-42-54" row is additionally checkable against a file this repository
//   did not produce: upstream's own test-high/expected/check-pcg32.out records the same
//   six leading outputs for the same seed.
//
//   Regenerating: tools/pcg-vectors/generate.sh   (needs a C compiler and network)
//   Verifying:    tools/pcg-vectors/generate.sh --check
// </auto-generated>

using System.Collections.Generic;

namespace RulesKernel.Randomness.Tests;

/// <summary>
/// PCG32 (<c>pcg_setseq_64_xsh_rr_32</c>) sequences taken from the reference
/// implementation. These are the replay contract: if a change here is not accompanied by
/// a decision superseding docs/decisions/0005, the change is a bug, because every stored seed in the
/// project means whatever this file says it means.
/// </summary>
public static class Pcg32ReferenceVectors
{
    /// <summary>The upstream commit the vectors were generated from.</summary>
    public const string UpstreamCommit = "bc39cd76ac3d541e618606bcc6e1e5ba5e5e6aa3";

    /// <summary>The upstream repository the reference implementation was fetched from.</summary>
    public const string UpstreamRepository = "https://github.com/imneme/pcg-c-basic";

    /// <summary>A sequence produced by seeding the reference with an explicit state and stream.</summary>
    /// <param name="Name">Identifies the row in assertion output.</param>
    /// <param name="InitState">The <c>initstate</c> argument to <c>pcg32_srandom_r</c>.</param>
    /// <param name="InitSequence">The <c>initseq</c> (stream selector) argument.</param>
    /// <param name="StateAfterSeed">The reference's internal state once seeding returned.</param>
    /// <param name="IncrementAfterSeed">The reference's internal increment once seeding returned.</param>
    /// <param name="Outputs">Consecutive <c>pcg32_random_r</c> results from that point.</param>
    public sealed record SeededVector(
        string Name,
        ulong InitState,
        ulong InitSequence,
        ulong StateAfterSeed,
        ulong IncrementAfterSeed,
        IReadOnlyList<uint> Outputs);

    /// <summary>A sequence produced by driving the reference from an explicit (state, increment) pair.</summary>
    /// <param name="Name">Identifies the row in assertion output.</param>
    /// <param name="State">The internal state the reference was started from.</param>
    /// <param name="Increment">The internal increment the reference was started from.</param>
    /// <param name="RotOfFirstDraw">The rotation the first draw applies; 0 and 31 are the edge cases.</param>
    /// <param name="Outputs">Consecutive <c>pcg32_random_r</c> results from that point.</param>
    /// <param name="StateAfter">The reference's internal state after those draws.</param>
    /// <param name="IncrementAfter">The reference's internal increment after those draws.</param>
    public sealed record RawStateVector(
        string Name,
        ulong State,
        ulong Increment,
        int RotOfFirstDraw,
        IReadOnlyList<uint> Outputs,
        ulong StateAfter,
        ulong IncrementAfter);

    /// <summary>A capture taken mid-sequence, with the draws that must follow it.</summary>
    /// <param name="Name">Identifies the row in assertion output.</param>
    /// <param name="InitState">The <c>initstate</c> argument to <c>pcg32_srandom_r</c>.</param>
    /// <param name="InitSequence">The <c>initseq</c> (stream selector) argument.</param>
    /// <param name="Skip">How many values were drawn and discarded before the capture.</param>
    /// <param name="StateAtCapture">The reference's internal state at that moment.</param>
    /// <param name="IncrementAtCapture">The reference's internal increment at that moment.</param>
    /// <param name="OutputsAfterCapture">Consecutive results the capture must go on to produce.</param>
    public sealed record ResumeVector(
        string Name,
        ulong InitState,
        ulong InitSequence,
        int Skip,
        ulong StateAtCapture,
        ulong IncrementAtCapture,
        IReadOnlyList<uint> OutputsAfterCapture);

    /// <summary>Sequences reached through the reference's own seeding routine.</summary>
    public static readonly IReadOnlyList<SeededVector> Seeded =
    [
        new(
            "canonical-42-54",
            0x000000000000002AUL,
            0x0000000000000036UL,
            0x185706B82C2E03F8UL,
            0x000000000000006DUL,
            [
                0xA15C02B7U, 0x7B47F409U, 0xBA1D3330U, 0x83D2F293U,
                0xBFA4784BU, 0xCBED606EU, 0xBFC6A3ADU, 0x812FFF6DU,
                0xE61F305AU, 0xF9384B90U, 0x32DB86FEU, 0x1DC035F9U,
                0xED786826U, 0x3822441DU, 0x2BA113D7U, 0x1C5B818BU
            ]),
        new(
            "zero-zero",
            0x0000000000000000UL,
            0x0000000000000000UL,
            0x5851F42D4C957F2EUL,
            0x0000000000000001UL,
            [
                0xE4C14788U, 0x379C6516U, 0x5C4AB3BBU, 0x601D23E0U,
                0x1C382B8CU, 0xD1FAAB16U, 0x67680A2DU, 0x92014A6EU,
                0x628AE389U, 0xA794034DU, 0x5CC38CD9U, 0xFC913A3BU,
                0x81C851DCU, 0x90C820E4U, 0x60DFA703U, 0xD613AE14U
            ]),
        new(
            "one-one",
            0x0000000000000001UL,
            0x0000000000000001UL,
            0x6147D0B53255FCB7UL,
            0x0000000000000003UL,
            [
                0xC9828F91U, 0x1592E274U, 0xC0262657U, 0xA5C2B6D3U,
                0xAF811256U, 0x6C1C2879U, 0x30130B26U, 0x9CC21C33U,
                0xD137EF42U, 0x908262ABU, 0xD24D7799U, 0xAA1118ABU,
                0xE16C3EBDU, 0xBD77A511U, 0x87D285E4U, 0x260276E8U
            ]),
        new(
            "max-state-max-seq",
            0xFFFFFFFFFFFFFFFFUL,
            0xFFFFFFFFFFFFFFFFUL,
            0x4F5C17A566D501A5UL,
            0xFFFFFFFFFFFFFFFFUL,
            [
                0x2675C047U, 0x7779A837U, 0xA145AA13U, 0x5F6BE726U,
                0x523C44C5U, 0x75A406D6U, 0xE6643B13U, 0x8E3D51A0U,
                0x45BDD0C6U, 0x157FD45CU, 0xC5899FC0U, 0x1F7821DFU,
                0x85E92559U, 0xBB68A3FFU, 0x1D80C5DEU, 0x80B7742FU
            ]),
        new(
            "high-entropy",
            0x853C49E6748FEA9BUL,
            0xDA3E39CB94B95BDBUL,
            0xEA1B84321029EE21UL,
            0xB47C73972972B7B7UL,
            [
                0x1BBEB4F2U, 0xE82E89E9U, 0x681CFDEBU, 0xE00FA2ECU,
                0xB1E1A434U, 0xBE56068DU, 0x2ADD8C94U, 0x9F1B63F5U,
                0x38BFE349U, 0xE5601E3DU, 0x66AD0BA4U, 0x6587FA97U,
                0x58CE0BBFU, 0xA76B235AU, 0xCA5A9C9BU, 0xE28A991BU
            ]),
        new(
            "stream-a",
            0x000000000000002AUL,
            0x0000000000000000UL,
            0xD5C4039BDD1C5C90UL,
            0x0000000000000001UL,
            [
                0x21B756EEU, 0xC15EF750U, 0x9548A9BDU, 0x35DB428DU,
                0xF0071649U, 0xA243807FU, 0xB4C5BDD2U, 0x103CA9D2U
            ]),
        new(
            "stream-b",
            0x000000000000002AUL,
            0x0000000000000001UL,
            0x8667EBF676475AECUL,
            0x0000000000000003UL,
            [
                0x4DF1CCF9U, 0xE5838752U, 0x58ED9E10U, 0xF3E37B51U,
                0xE7664374U, 0x6AFDE4A8U, 0x8712391EU, 0x738FC318U
            ]),
        new(
            "stream-c",
            0x000000000000002AUL,
            0x0000000000000002UL,
            0x370BD4510F725948UL,
            0x0000000000000005UL,
            [
                0xFF85ECC9U, 0x4DE4D2F6U, 0x72EB3394U, 0x16EE6127U,
                0x1586AAD8U, 0xB055098AU, 0x059D0E23U, 0xEAF2D20FU
            ]),
    ];

    /// <summary>Sequences reached by restoring an explicit internal state.</summary>
    public static readonly IReadOnlyList<RawStateVector> RawState =
    [
        new(
            "initializer",
            0x853C49E6748FEA9BUL,
            0xDA3E39CB94B95BDBUL,
            16,
            [
                0x152CA78DU, 0x027C6003U, 0xCB07BBF3U, 0xF98BEFEEU,
                0x1CD777E3U, 0xA4E29590U, 0x661E4B6DU, 0x093B9E0EU
            ],
            0xEDB7D2E8E8DB69C3UL,
            0xDA3E39CB94B95BDBUL),
        new(
            "rot-zero",
            0x0000000000000000UL,
            0x0000000000000001UL,
            0,
            [
                0x00000000U, 0x00000000U, 0xE4C14788U, 0x379C6516U,
                0x5C4AB3BBU, 0x601D23E0U, 0x1C382B8CU, 0xD1FAAB16U
            ],
            0x9A8B7F78DA6EF4D8UL,
            0x0000000000000001UL),
        new(
            "rot-max",
            0xFFFFFFFFFFFFFFFFUL,
            0x0000000000000001UL,
            31,
            [
                0xFFF00001U, 0x44726F5CU, 0xF26077DFU, 0x87198AD6U,
                0x447BC403U, 0xABF65840U, 0x31F8D5EBU, 0x2468AEDEU
            ],
            0xE4EDA519A22DB7B7UL,
            0x0000000000000001UL),
    ];

    /// <summary>Mid-sequence captures and the draws that must follow them.</summary>
    public static readonly IReadOnlyList<ResumeVector> Resume =
    [
        new(
            "resume-42-54",
            0x000000000000002AUL,
            0x0000000000000036UL,
            5,
            0x8303569FBE80C471UL,
            0x000000000000006DUL,
            [
                0xCBED606EU, 0xBFC6A3ADU, 0x812FFF6DU, 0xE61F305AU,
                0xF9384B90U, 0x32DB86FEU, 0x1DC035F9U, 0xED786826U
            ]),
        new(
            "resume-canonical-long",
            0x000000000000002AUL,
            0x0000000000000036UL,
            100,
            0xAB39B0AF88701234UL,
            0x000000000000006DUL,
            [
                0x9A61E339U, 0xE7DE4CB5U, 0xA875DB4AU, 0x5D73F2B6U,
                0x5D9838F5U, 0x22ACC9E6U, 0xB1C6C855U, 0x68D0FA8BU
            ]),
    ];
}
